export { default as Navbar } from './Navbar';
export { default as Homepage } from './Homepage';
export { default as Currencies } from './Currencies';
export { default as CryptoDetails } from './CryptoDetails';
export { default as Exchanges } from './Exchanges';
export { default as News } from './News';
export { default as MarketPlace } from './MarketPlace';
export { default as Minted } from './Minted';
export { default as Lottery } from './Lottery';